"""Textos da interface e do conteúdo gerado em cada idioma suportado."""

from __future__ import annotations

IDIOMA_PADRAO = "pt_BR"
IDIOMAS_SUPORTADOS = ("pt_BR", "en")

NOMES_IDIOMAS = {
    "pt_BR": "Português (Brasil)",
    "en": "English",
}

TRADUCOES = {
    "pt_BR": {
        # Geral
        "titulo_app": "Leitor de Projetos",
        "titulo_janela": "Leitor de Projetos {versao}",
        "fechar": "Fechar",
        "continuar": "Continuar",
        "cancelar": "Cancelar",
        "adicionar": "Adicionar",
        "remover": "Remover",
        "restaurar_padrao": "Restaurar padrão",

        # Janela principal
        "descricao_app": "Ferramenta para transformar projetos de código em arquivos de texto\npara análise, compartilhamento e uso com IAs.",
        "configuracoes": "Configurações",
        "ajuda": "Ajuda",
        "historico": "Histórico",
        "projeto_selecionado": "Projeto selecionado",
        "selecionar_pasta": "Selecionar pasta",
        "abrir_pasta": "Abrir pasta",
        "pre_visualizar_arquivos": "Pré-visualizar arquivos",
        "nenhuma_pasta_selecionada": "Nenhuma pasta selecionada. Escolha um projeto para começar.",
        "modo_processamento": "Modo de processamento",
        "modo_arquivo_unico": "Arquivo único",
        "modo_arquivos_separados": "Arquivos separados",
        "descricao_arquivo_unico": "Cria um único arquivo TXT contendo a estrutura e o conteúdo dos arquivos selecionados.",
        "descricao_arquivos_separados": "Cria arquivos TXT separados para cada arquivo de código encontrado.",
        "pasta_destino": "Pasta de destino",
        "selecionar_pasta_saida": "Selecionar pasta de saída",
        "padrao_caminho": "Padrão: {caminho}",
        "processando_projeto": "Processando projeto...",
        "gerar_arquivos": "Gerar arquivos",
        "selecionar_pasta_projeto_titulo": "Selecionar pasta do projeto",
        "selecionar_pasta_destino_titulo": "Selecionar pasta de destino",
        "pasta_nao_encontrada": "Pasta não encontrada",
        "selecione_pasta_valida": "Selecione uma pasta válida primeiro.",
        "nenhum_projeto_selecionado": "Nenhum projeto selecionado",
        "selecione_projeto_primeiro": "Selecione uma pasta de projeto primeiro.",
        "pasta_invalida": "Pasta inválida",
        "pasta_projeto_nao_existe": "A pasta do projeto selecionada não existe mais.",
        "em_andamento": "Em andamento",
        "processamento_em_execucao": "Já existe um processamento em execução.",
        "arquivo_atual": "Arquivo atual:\n{arquivo}",
        "aviso_nao_foi_possivel_ler": "[AVISO] Não foi possível ler: {caminho} — {motivo}",
        "erro_processamento": "Erro no processamento",
        "ocorreu_erro": "Ocorreu um erro:\n{erro}",
        "transferencia_concluida": "Transferência concluída",
        "transferencia_concluida_check": "✓  Transferência concluída",
        "arquivos_gerados_sucesso": "Os arquivos foram gerados com sucesso.",
        "encontrados": "ENCONTRADOS",
        "processados": "PROCESSADOS",
        "ignorados": "IGNORADOS",
        "erros": "ERROS",
        "salvo_em": "Salvo em",
        "abrir_local_resultado": "Abrir local do resultado",
        "fechar_aplicativo": "Fechar aplicativo",
        "prefixo_arquivo_saida": "arquivo",
        "prefixo_resumo_saida": "resumo",

        # Configurações
        "titulo_configuracoes": "Configurações",
        "aba_extensoes": "Extensões",
        "aba_ignorados": "Pastas e arquivos ignorados",
        "aba_idioma": "Idioma",
        "modo_arquivo_unico_titulo": "Modo: Arquivo único",
        "modo_arquivos_separados_titulo": "Modo: Arquivos separados",
        "adicionar_extensao": "Adicionar extensão",
        "extensao_exemplo": "Extensão (ex: .rb):",
        "pastas_ignoradas": "Pastas ignoradas",
        "arquivos_ignorados": "Arquivos ignorados",
        "arquivo_protegido_info": '"{arquivo}" é sempre protegido e não pode ser removido.',
        "adicionar_pasta_ignorada": "Adicionar pasta ignorada",
        "nome_pasta": "Nome da pasta:",
        "adicionar_arquivo_ignorado": "Adicionar arquivo ignorado",
        "nome_arquivo": "Nome do arquivo:",
        "nao_permitido": "Não permitido",
        "arquivo_protegido_erro": '"{arquivo}" é protegido por padrão e não pode ser removido.',
        "idioma_interface": "Idioma da interface",
        "idioma_info": "A alteração é aplicada ao fechar esta janela e será lembrada na próxima vez que o aplicativo abrir.",

        # Pré-visualização
        "pre_visualizacao": "Pré-visualização",
        "arquivos_encontrados": "Arquivos encontrados: {total}",
        "selecione_arquivos_processar": "Selecione os arquivos que deverão ser processados.",
        "confirmar_selecao": "Confirmar seleção",

        # Confirmação
        "confirmar_processamento": "Confirmar processamento",
        "serao_processados": "Serão processados {total} arquivos.",
        "sensiveis_ignorados": "Arquivos sensíveis ignorados: {total}.",
        "nenhum_sensivel": "Nenhum arquivo sensível encontrado.",
        "deseja_continuar": "Deseja continuar?",

        # Ajuda
        "sobre_ajuda": "Sobre / Ajuda",
        "ajuda_cabecalho": "Leitor de Projetos {versao}\n",
        "ajuda_windows": "Aplicativo para Windows.\n\n",
        "ajuda_para_que_serve_titulo": "Para que serve\n",
        "ajuda_para_que_serve": "Transforma projetos de código em arquivos de texto, para análise, documentação, compartilhamento e envio para ferramentas de IA.\n\n",
        "ajuda_modos_titulo": "Arquivo único × Arquivos separados\n",
        "ajuda_modos": "Arquivo único: gera um único .txt com a árvore de pastas e o conteúdo de todos os arquivos.\nArquivos separados: gera um .txt para cada arquivo de código, preservando a estrutura de pastas.\n\n",
        "ajuda_selecionar_titulo": "Como selecionar um projeto\n",
        "ajuda_selecionar": 'Clique em "Selecionar pasta" na seção Projeto e escolha a pasta raiz do seu código.\n\n',
        "ajuda_extensoes_titulo": "Como configurar extensões\n",
        "ajuda_extensoes": "Em Configurações, adicione ou remova extensões de arquivo que devem ser lidas. Cada modo mantém sua própria lista.\n\n",
        "ajuda_ignorados_titulo": "Como configurar itens ignorados\n",
        "ajuda_ignorados": "Em Configurações, adicione nomes de pastas ou arquivos que nunca devem ser processados.\n\n",
        "ajuda_env_titulo": "Por que .env é ignorado\n",
        "ajuda_env": "Arquivos .env costumam conter senhas, chaves de API e tokens. Por segurança, são sempre bloqueados, mesmo que sua extensão esteja na lista permitida.\n\n",
        "ajuda_saida_titulo": "Onde os resultados são salvos\n",
        "ajuda_saida": "Na pasta de destino escolhida, ou em uma pasta padrão na Área de Trabalho caso nenhuma seja informada.\n",

        # Histórico
        "nenhum_processamento": "Nenhum processamento realizado ainda.",
        "historico_linha": "{data} — {projeto} — {quantidade} arquivos — {modo}\n",
        "limpar_historico": "Limpar histórico",

        # Conteúdo gerado / processadores
        "resumo_projeto": "RESUMO DO PROJETO: {caminho}\n\n",
        "arquivo_saida": "ARQUIVO: {nome}\n",
        "conteudo_saida": "CONTEÚDO:\n",
        "aviso_leitura_saida": "[AVISO] Não foi possível ler. Motivo: {motivo}\n\n",
        "arquivo_original": "Arquivo original: {nome}\n\n",
        "conteudo_arquivo": "Conteúdo:\n\n",
        "acesso_negado": "Acesso negado.",
        "arquivo_nao_texto": "Arquivo não é texto legível (possível binário).",
    },
    "en": {
        # General
        "titulo_app": "Project Reader",
        "titulo_janela": "Project Reader {versao}",
        "fechar": "Close",
        "continuar": "Continue",
        "cancelar": "Cancel",
        "adicionar": "Add",
        "remover": "Remove",
        "restaurar_padrao": "Restore defaults",

        # Main window
        "descricao_app": "Tool for converting code projects into text files\nfor analysis, sharing, and use with AI tools.",
        "configuracoes": "Settings",
        "ajuda": "Help",
        "historico": "History",
        "projeto_selecionado": "Selected project",
        "selecionar_pasta": "Select folder",
        "abrir_pasta": "Open folder",
        "pre_visualizar_arquivos": "Preview files",
        "nenhuma_pasta_selecionada": "No folder selected. Choose a project to get started.",
        "modo_processamento": "Processing mode",
        "modo_arquivo_unico": "Single file",
        "modo_arquivos_separados": "Separate files",
        "descricao_arquivo_unico": "Creates a single TXT file containing the structure and content of the selected files.",
        "descricao_arquivos_separados": "Creates separate TXT files for each code file found.",
        "pasta_destino": "Output folder",
        "selecionar_pasta_saida": "Select output folder",
        "padrao_caminho": "Default: {caminho}",
        "processando_projeto": "Processing project...",
        "gerar_arquivos": "Generate files",
        "selecionar_pasta_projeto_titulo": "Select project folder",
        "selecionar_pasta_destino_titulo": "Select output folder",
        "pasta_nao_encontrada": "Folder not found",
        "selecione_pasta_valida": "Select a valid folder first.",
        "nenhum_projeto_selecionado": "No project selected",
        "selecione_projeto_primeiro": "Select a project folder first.",
        "pasta_invalida": "Invalid folder",
        "pasta_projeto_nao_existe": "The selected project folder no longer exists.",
        "em_andamento": "In progress",
        "processamento_em_execucao": "A processing task is already running.",
        "arquivo_atual": "Current file:\n{arquivo}",
        "aviso_nao_foi_possivel_ler": "[WARNING] Could not read: {caminho} — {motivo}",
        "erro_processamento": "Processing error",
        "ocorreu_erro": "An error occurred:\n{erro}",
        "transferencia_concluida": "Transfer complete",
        "transferencia_concluida_check": "✓  Transfer complete",
        "arquivos_gerados_sucesso": "The files were generated successfully.",
        "encontrados": "FOUND",
        "processados": "PROCESSED",
        "ignorados": "IGNORED",
        "erros": "ERRORS",
        "salvo_em": "Saved to",
        "abrir_local_resultado": "Open result location",
        "fechar_aplicativo": "Close application",
        "prefixo_arquivo_saida": "file",
        "prefixo_resumo_saida": "summary",

        # Settings
        "titulo_configuracoes": "Settings",
        "aba_extensoes": "Extensions",
        "aba_ignorados": "Ignored folders and files",
        "aba_idioma": "Language",
        "modo_arquivo_unico_titulo": "Mode: Single file",
        "modo_arquivos_separados_titulo": "Mode: Separate files",
        "adicionar_extensao": "Add extension",
        "extensao_exemplo": "Extension (e.g. .rb):",
        "pastas_ignoradas": "Ignored folders",
        "arquivos_ignorados": "Ignored files",
        "arquivo_protegido_info": '"{arquivo}" is always protected and cannot be removed.',
        "adicionar_pasta_ignorada": "Add ignored folder",
        "nome_pasta": "Folder name:",
        "adicionar_arquivo_ignorado": "Add ignored file",
        "nome_arquivo": "File name:",
        "nao_permitido": "Not allowed",
        "arquivo_protegido_erro": '"{arquivo}" is protected by default and cannot be removed.',
        "idioma_interface": "Interface language",
        "idioma_info": "The change is applied when you close this window and will be remembered the next time the application opens.",

        # Preview
        "pre_visualizacao": "Preview",
        "arquivos_encontrados": "Files found: {total}",
        "selecione_arquivos_processar": "Select the files that should be processed.",
        "confirmar_selecao": "Confirm selection",

        # Confirmation
        "confirmar_processamento": "Confirm processing",
        "serao_processados": "{total} files will be processed.",
        "sensiveis_ignorados": "Sensitive files ignored: {total}.",
        "nenhum_sensivel": "No sensitive files found.",
        "deseja_continuar": "Do you want to continue?",

        # Help
        "sobre_ajuda": "About / Help",
        "ajuda_cabecalho": "Project Reader {versao}\n",
        "ajuda_windows": "Windows application.\n\n",
        "ajuda_para_que_serve_titulo": "What it does\n",
        "ajuda_para_que_serve": "Converts code projects into text files for analysis, documentation, sharing, and use with AI tools.\n\n",
        "ajuda_modos_titulo": "Single file × Separate files\n",
        "ajuda_modos": "Single file: generates one .txt file with the folder tree and the content of all selected files.\nSeparate files: generates one .txt file for each code file while preserving the folder structure.\n\n",
        "ajuda_selecionar_titulo": "How to select a project\n",
        "ajuda_selecionar": 'Click "Select folder" in the Project section and choose the root folder of your code.\n\n',
        "ajuda_extensoes_titulo": "How to configure extensions\n",
        "ajuda_extensoes": "In Settings, add or remove the file extensions that should be read. Each mode keeps its own list.\n\n",
        "ajuda_ignorados_titulo": "How to configure ignored items\n",
        "ajuda_ignorados": "In Settings, add folder or file names that should never be processed.\n\n",
        "ajuda_env_titulo": "Why .env is ignored\n",
        "ajuda_env": ".env files often contain passwords, API keys, and tokens. For security, they are always blocked even if their extension is allowed.\n\n",
        "ajuda_saida_titulo": "Where results are saved\n",
        "ajuda_saida": "Results are saved in the selected output folder, or in a default Desktop folder if none is provided.\n",

        # History
        "nenhum_processamento": "No processing has been performed yet.",
        "historico_linha": "{data} — {projeto} — {quantidade} files — {modo}\n",
        "limpar_historico": "Clear history",

        # Generated content / processors
        "resumo_projeto": "PROJECT SUMMARY: {caminho}\n\n",
        "arquivo_saida": "FILE: {nome}\n",
        "conteudo_saida": "CONTENT:\n",
        "aviso_leitura_saida": "[WARNING] Could not read. Reason: {motivo}\n\n",
        "arquivo_original": "Original file: {nome}\n\n",
        "conteudo_arquivo": "Content:\n\n",
        "acesso_negado": "Access denied.",
        "arquivo_nao_texto": "File is not readable text (possibly binary).",
    },
}


def traduzir(chave: str, idioma: str, **valores: object) -> str:
    """Retorna um texto traduzido, com fallback seguro para pt_BR."""
    tabela = TRADUCOES.get(idioma, TRADUCOES[IDIOMA_PADRAO])
    texto = tabela.get(chave, TRADUCOES[IDIOMA_PADRAO].get(chave, chave))
    return texto.format(**valores) if valores else texto
